### PR TITLE
Feat android broadcastreceiver

### PR DESCRIPTION
**Pull request by reime005**
I've implemented the BroadcastReceiver for background uploads on Android. This should solve some 'connection lost' issues but also means that the receiver is registered in the application.

Also made it possible to set maxRetries (see #124) on Android.

I wouldn't feel comfortable to merge that before someone else tested it.

Fixes: #129 #103

### CODE REVIEW

**Comment by ARDcode** [comment]
not work on background :(

**Comment by reime005** [comment]
> @reime005, not work on background :(

can you add this to your AndroidManifest.xml:

```
<receiver android:name="com.vydia.RNUploader.UploadReceiver" android:exported="false">
    <intent-filter>
        <action android:name="com.vydia.RNUploader.uploadservice.broadcast.status" />
    </intent-filter>
</receiver>
```

and try it again?

**Comment by KaarelKa** [comment]
@reime005 

Not sure if this helps but I used this version in my app, because with version 5.0.1 I got #103 and with version 4.4.0 it crashed on Samsung Xcover 4 - Android 8.1 ( probably related to #87 ).

On Samsung Xcover 4 - Android 8.1 this worked perfectly (Without adding receiver to Android Manifest)
On Xiaomi Redmi 4a - Android 7.1.2 the upload continued on background, but progress was not emitted.

i removed unregistering in onHostPause, which worked for my use case.
```
 @Override
  public void onHostPause() {
    try {
      // uploadReceiver.unregister(reactContext);
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
```

I'm guessing onHostPause got called, when app went from foreground to background.

Hope this helps.

**Comment by StevePotter** [comment]
@reime005 I'll test on the sample app soon.  Fingers crossed!

**Comment by defualt** [comment]
Confirming these fixes in my app.

My Android uploads to S3 were reporting progress until a certain point and then the progress reporting would stop and completed listener would not fire.  The upload was actually completing and appearing in my bucket.

I tried this PR and it solved the listener problem when always foreground.  But when backgrounding the app, the completed listener wouldn't fire when returning to the app.  I modified the code as suggested by @KaarelKa and that fixed it.

**Comment by reime005** [comment]
> Confirming these fixes in my app.
> 
> My Android uploads to S3 were reporting progress until a certain point and then the progress reporting would stop and completed listener would not fire. The upload was actually completing and appearing in my bucket.
> 
> I tried this PR and it solved the listener problem when always foreground. But when backgrounding the app, the completed listener wouldn't fire when returning to the app. I modified the code as suggested by @KaarelKa and that fixed it.

I can confirm that!

**Comment by webismymain** [comment]
I can confirm this PR works!

Tested on Android and did about 20 uploads and all of them emitted the completed and progress event correctly.

**Comment by mths0x5f** [comment]
@reime005 @StevePotter  I installed this PR with `npm install Vydia/react-native-background-upload#pull/133/head` and I can confirm it resolved my issues with the events not triggering.

**However**, I had to copy n paste @KaarelKa snippet back, because you cannot simply remove the override method... UploaderModule is not abstract:

```stacktrace
/node_modules/react-native-background-upload/android/src/main/java/com/vydia/UploaderModule.java:40: error: UploaderModule is not abstract and does not override abstract method onHostPause() in LifecycleEventListener
public class UploaderModule extends ReactContextBaseJavaModule implements LifecycleEventListener {
```

I'll be using this for while because the way I'm using the library, the responseBody is really valuable for me, retrieving the uploaded file id from there.

**Comment by TSMMark** [comment]
Sounds like @KaarelKa has posted some code that we need to include in this PR, is that right?

After that, I'm happy to merge and release this if y'all are confident in the testing that's been done.

**Comment by reime005** [comment]
@TSMMark  done

**Comment by TSMMark** [comment]
@reime005 Awesome. Looking good to merge soon!

Is this something that needs to be added to the docs?

> > @reime005, not work on background :(
> 
> can you add this to your AndroidManifest.xml:
> 
> ```
> <receiver android:name="com.vydia.RNUploader.UploadReceiver" android:exported="false">
>     <intent-filter>
>         <action android:name="com.vydia.RNUploader.uploadservice.broadcast.status" />
>     </intent-filter>
> </receiver>
> ```
> 
> and try it again?

And are there any other setup steps that need to be included in documentation?

**Comment by reime005** [comment]
From my perspective, the documentation is fine. Regarding the manifest thing: we use a context-registered broadcast receiver. So we don't need to declare it in the manifest. See [Android doc](https://developer.android.com/guide/components/broadcasts#manifest-declared-receivers)

**Comment by rdgomt** [comment]
Hello! Is this PR still open? I would like to set max retries in my app.

**Comment by reime005** [comment]
Closed by #163

**Pull request closed without merging**
