### PR TITLE
Upgrade android-upload-service to 4.3.0

### PR DESCRIPTION
**Pull request by allinelara**
I upgraded android-upload-service to 4.3.0, because version 3.4.2 is not maintain anymore. For the implementation I followed the setup description in https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads.

**min Sdk Version 21**

This change just impacts Android. 

This PR is related to #162 

## Test Plan
I tested in Samsung S10+ Android 10. But I am still testing. 

It will be nice if someone could test this PR too. 

## Compatibility

 iOS:   ❌     
Android:   ✅

### CODE REVIEW

**Comment by reime005** [comment]
it would be great if this could be tested so that we know that it works. this would cause a breaking change. some documentation may also be needed

**Comment by pribeh** [comment]
bump. sorry

**Comment by benesing** [comment]
Thank you @allinelara! In the current release, I am seeing the 'completed' notification fail often, and this is now working reliably.

I did find a bug. On uploading a second file, the 'completed' notification is sent twice. On the third file, it's sent three times, and so on. I've worked around that, and this has gone out to my alpha testers.

Galaxy S6 running Android 7.0
Galaxy S7A running Android 7.0

**Comment by allinelara** [comment]
@benesing can you share your fix?

**Comment by benesing** [comment]
@allinelara I'm just checking a unique ID in the 'completed' handler, not a real fix. I'll take look at the module itself.

**Comment by allinelara** [comment]
@benesing it should be fixed

**Comment by benesing** [comment]
@allinelara I checked with your update and it's fixed. Thank you! I have a handful of people using in the field and I'll report back if I find any problems.

**Comment by reime005** [comment]
@TSMMark this has been running in production for 3 weeks now, looks good. I'd suggest a merge + major version bump

**Pull request merged**
