### PR TITLE
Add CocoaPods support

### PR DESCRIPTION
**Pull request by kdawgwilk**
This fixes the header not found when using CocoaPods

### CODE REVIEW

**Comment by davidfant** [comment]
I can confirm that this works 👍

**Comment by TSMMark** [comment]
I've been away from this for a while what's the purpose of this?

**Comment by kdawgwilk** [comment]
Allows this library to be used in an app that uses CocoaPods for RN native as seen here http://facebook.github.io/react-native/docs/integration-with-existing-apps#configuring-cocoapods-dependencies.  Otherwise the imports in this lib will fail to find the react-native headers

**Comment by StevePotter** [comment]
Merged.  Hopefully this works

**Pull request merged**
