### PR TITLE
Parameters support & UP CC

### PR DESCRIPTION
**Pull request by ovr**

### CODE REVIEW

**Comment by TSMMark** [comment]
Good stuff @ovr. Please update readme and if possible add to [ReactNativeBackgroundUploadExample](https://github.com/Vydia/ReactNativeBackgroundUploadExample) and I'll test it out.

**Comment by TSMMark** [comment]
Hey @ovr we're getting a good amount of requests for this now. Is there anything else you wanted to add to this? I can probably set some time to add to the example app soon if you are too busy.

**Comment by OzoTek** [comment]
Hi,

Any news on this?

Cheers.

**Comment by reidab** [comment]
Just came across this while trying to figure out presigned multipart POST uploads to S3. It would be great to see either this PR or the thoughtbot implementation mentioned above merged.

**Comment by TSMMark** [comment]
@reidab Agreed. In the meantime you can use HTTP headers if needed.

**Comment by ovr** [comment]
BTW, I rebased this PR, it's green @TSMMark can you merge it and release? Possible we can add demo example in feature when anyone will have a free time

**Comment by StevePotter** [comment]
@ovr it's merged and published to npm@4.4.0.  Thanks for your work on this!

**Comment by ovr** [comment]
@StevePotter Thank you 👍

**Pull request merged**
