### PR TITLE
Video uploads larger than ~100MB fail on iOS

### PR DESCRIPTION
**Pull request by kasterlod**
# Summary
* What issues does the pull request solve? *
#172 
#149 
#53 
#93 

## Test Plan
Large files to upload as a multipart. Size limit depends on device type, tested well with even over 2gb files. Without these changes, it's failing around 100mb.

### What's required for testing (prerequisites)?
Prepare large file (f.e. 1gb video file)
Prepare remote server for uploading.

### What are the steps to reproduce (after prerequisites)?
Try to upload large file as a multipart to your remote server with success.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I've added Detox End-to-End Test(s)
- [ ] I've created a snack to demonstrate the changes: LINK HERE

### CODE REVIEW

**Comment by pmella16** [comment]
try to change 
          headers: {
           'content-type': 'multipart/form-data' // change for 'Content-Type': 'video/mp4',
          },

**Comment by reime005** [comment]
@kasterlod can you do a rebase?

**Comment by burger-digital-dev** [comment]
@reime005 This PR appears to break background upload. When you upload then background the application it will crash.

**Comment by xHeinrich** [comment]
@reime005 This appears to break background upload on ios(Causes a hard crash). Can replicate by uploading and while uploading background the application.

**Pull request merged**
