### PR TITLE
Adding Test App and E2E tests

### PR DESCRIPTION
**Pull request by reime005**
This PR adds a very basic app setup for testing this repository. To make this app work, I had to disable the automatic dependency linking. Server-side I've created a simple express.js server, that has to be started separately, see README.  

The Android tests do not fully work, but iOS work fine for me.

The App has two buttons that do calls against a server (upload with response 200 and 502). This could be extended in the future.

### CODE REVIEW

**Comment by TSMMark** [comment]
Thanks @reime005 please consider merging with https://github.com/Vydia/ReactNativeBackgroundUploadExample or update readme if not obvious enough in the readme to know it exists

**Comment by reime005** [comment]
@TSMMark  Oh, I haven't seen that. Should have read the readme more I guess. But anyway, don't you think that tests should be included in the main repository, so that you don't have to use a separate codebase just for testing?

**Comment by reime005** [comment]
This file: TestApp/e2e/upload.e2e.js includes some very simple tests. I will merge the example app into this branch

**Comment by reime005** [comment]
@TSMMark I've merged the example app into this repo, added E2E tests for both platforms and added Github Actions CI/CD with semantic-release. Would be great if you could check it out and configure the NPM_TOKEN (Settings -> Secrets) as well as enable Github branch-protection to require successful checks for a pull request

**Pull request merged**
