### PR TITLE
Add index.d.ts file with Typescript bindings

### PR DESCRIPTION
**Pull request by Palid**
A lot of projects are using Typescript now and this package doesn't have it's own separate @types package, so I just wrote types for this one. You're welcome! :)

### CODE REVIEW

**Comment by sammarks** [comment]
Heads up, I think these typings are wrong. I'm using version 5.4.0 with my own custom types, and upgrading to >= 5.5.0 completely breaks the usage.

I'm not putting up a separate PR because my types aren't complete, but here were my types for reference:

```ts
declare module 'react-native-background-upload' {
  // We're not using this for now, so will always be enabled: false.
  import { EventSubscription } from 'react-native'

  export interface AndroidNotificationOptions {
    enabled?: boolean
    onProgressTitle?: string
    autoClear?: true
  }
  export interface UploadOptions {
    url: string
    path: string
    method: string
    type: 'raw' | 'multipart'
    maxRetries?: number
    headers?: {
      [header: string]: string
    }
    field?: string
    parameters?: {
      [param: string]: string
    }
    notification?: AndroidNotificationOptions
    useUtf8Charset?: boolean
  }
  export interface ProgressData {
    id: string
    // From 0 - 100, not a decimal.
    progress: number
  }
  export interface ErrorData {
    id: string
    error: Error
  }
  export interface CompleteData {
    id: string
    responseCode: number
    responseBody: object
  }
  export interface CancelledData {
    id: string
  }
  export function startUpload(options: UploadOptions): Promise<string>
  export function addListener(
    event: 'progress',
    uploadId: string | null,
    callback: (data: ProgressData) => any,
  ): EventSubscription
  export function addListener(
    event: 'error',
    uploadId: string | null,
    callback: (data: ErrorData) => any,
  ): EventSubscription
  export function addListener(
    event: 'cancelled',
    uploadId: string | null,
    callback: (data: CancelledData) => any,
  ): EventSubscription
  export function addListener(
    event: 'completed',
    uploadId: string | null,
    callback: (data: CompleteData) => any,
  ): EventSubscription
  export function cancelUpload(uploadId: string): Promise<boolean>
  export type FileInfo =
    | {
        name: string
        exists: boolean
      }
    | {
        exists: true
        size: number
        extension: string
        mimeType: string
      }
  export function getFileInfo(path: string): Promise<FileInfo>
}
```

**Comment by Palid** [comment]
@sammarks what's wrong with those typings? From what I see in the typings you have provided, mine are missing a couple of fields. Is that the case? If that's the case, could you kindly make a pull request with the missing fields that break on your side?

**Comment by Palid** [comment]
@sammarks Additionally fixed in https://github.com/Vydia/react-native-background-upload/pull/198

**Comment by sammarks** [comment]
@Palid the most notable change is the `addListener()` functions don't include a reference to a callback function but instead look like they contain part of the definition for the callback function instead.

**Comment by Palid** [comment]
@sammarks you're right! Haven't noticed that, will do the changes too in my PR. :)

**Comment by Palid** [comment]
@sammarks I think you can safely use https://github.com/Vydia/react-native-background-upload/pull/198/commits/9eb55a59a4195f45dd95de51ed15f22b78bf45a3 temporarily until it gets merged. Thanks for letting me know! Those types were only 'working' because I accidentally added `static addListener(event: UploadListenerEvent, uploadId: uploadId, callback: (data: object) => void ): void` in there which was pretty much a catchall. Good catch!

**Pull request merged**
