### PR TITLE
Update Kotlin Version to 1.6.20

### PR DESCRIPTION
**Pull request by TheUltDev**
Fixes React Native 0.72

### CODE REVIEW

**Comment by AlkanV** [comment]
this is need for apps that using gradle version 7.3 or above. including me i believe there are multiple projects awaiting this PR to be merged. for example, i did manual modifications on node_modules to make it work. Can we merge this PR as soon as possible? 
Thanks

**Comment by AlkanV** [comment]
@reime005 hey, could you please take a look at this PR?

thanks

**Comment by JonathanColetti** [comment]
The error for this incase anyone was wondering is `The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher`

**Comment by cchampou** [comment]
@TheUltDev I'll be using your branch in my project, since I have the same issue and this may work pretty well.

**Comment by TheUltDev** [comment]
Closing this since it's a duplicate of #320 which is a more permanent solution.

**Comment by dusanristic** [comment]
I believe this is not a duplication of #320. If you check [what has changed](https://github.com/Vydia/react-native-background-upload/pull/320/files), it's only the way we set the Kotlin version, whereas this issue is focused on upgrading Kotlin to 1.6.20. Merging #320 will not solve the problem we are currently facing; in other words, it will not update the Kotlin version.

**Comment by Hasham24** [comment]
Still encountering this problem with React Native version 0.72.8, and the error persists as follows:Screenshot 2024-01-09 at 4 37 31 PM

**Pull request closed without merging**
